# å†™åœ¨è¿™é‡Œçš„ç›®çš„æ˜¯ä¸ºäº†è®©æ•´ä¸ªé¡¹ç›®çš„ build.gradle.kts å’Œ build_-ogic çš„éƒ½èƒ½ç»Ÿä¸€è®¾ç½®ç‰ˆæœ¬å·
# å¦‚æœæ˜¯åªæœ‰æ¨¡å—ä½¿ç”¨çš„è¯ï¼Œå»ºè®®å†™åœ¨ build-logic/core/versions/ é‡Œé¢ï¼Œä¸€å®šè¦å†™å¥½å¯¹åº”ä¾èµ–çš„é“¾æ¥!!!

[versions]
javaTarget = "11" # 17 ç›®å‰ R8 è¿˜ä¸æ”¯æŒ sealedï¼Œæš‚æ—¶ä¸å‡çº§
kotlinJvmTarget = "11"
####################################################################################################
#                                            Android
####################################################################################################
agp = "8.5.2"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-appcompat = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle = "2.8.7"
# https://developer.android.com/jetpack/androidx/releases/core
androidx-core-ktx = "1.15.0"
# https://developer.android.com/jetpack/androidx/releases/core
androidx-core-animation = "1.0.0"
# https://developer.android.com/kotlin/ktx/extensions-list#androidxcollection
androidx-collection-ktx = "1.4.5"
# https://developer.android.com/jetpack/androidx/releases/fragment
androidx-fragment-ktx = "1.8.5"
# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activity-ktx = "1.9.3"
# https://mvnrepository.com/artifact/androidx.databinding/databinding-runtime
androidx-databinding = "8.7.2"
# https://developer.android.com/jetpack/androidx/releases/paging
androidx-paging = "3.3.2"
# https://developer.android.com/jetpack/androidx/releases/room
androidx-room = "2.6.1"
# https://developer.android.com/jetpack/androidx/releases/work
androidx-work = "2.10.0"

####################################################################################################
#                                              æ§ä»¶
####################################################################################################
# https://developer.android.com/jetpack/androidx/releases/constraintlayout
androidx-constraintlayout = "2.2.0"
# https://developer.android.com/jetpack/androidx/releases/recyclerview
androidx-recyclerview = "1.3.2"
# https://developer.android.com/jetpack/androidx/releases/cardview
androidx-cardview = "1.0.0"
# https://developer.android.com/jetpack/androidx/releases/viewpager2
androidx-viewpager2 = "1.1.0"
# https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout
androidx-swiperefreshlayout = "1.1.0"
# https://github.com/material-components/material-components-android
material = "1.12.0"
# https://github.com/google/flexbox-layout
flexbox = "3.0.0"
# https://lottiefiles.com/blog/working-with-lottie/getting-started-with-lottie-animations-in-android-app
# æœ€æ–°ç‰ˆæœ¬å·è¯·æŸ¥çœ‹ï¼šhttps://mvnrepository.com/artifact/com.airbnb.android/lottie
lottie = "6.6.0"
# https://github.com/Baseflow/PhotoView
# æŸ¥çœ‹å›¾ç‰‡çš„æ§ä»¶ï¼Œæ”¯æŒåŒæŒ‡ç¼©æ”¾ï¼Œä½†æœ€åæ›´æ–°æ˜¯ 17 å¹´
photoView = "2.3.0"
# https://github.com/985892345/NetLayout
# 20 çº§éƒ­ç¥¥ç‘å°è£…çš„è¯¾è¡¨åº•å±‚æ§ä»¶ï¼Œå¦‚æœæœ‰é—®é¢˜ï¼Œæ¬¢è¿æ¥è”ç³» ğŸ‘€
netLayout = "1.1.1-SNAPSHOT"
# https://github.com/985892345/SlideShow
# 20 çº§éƒ­ç¥¥ç‘å°è£…çš„ Banner åº“ï¼Œå¦‚æœæœ‰é—®é¢˜ï¼Œæ¬¢è¿æ¥è”ç³» ğŸ‘€
slideShow = "2.0.1"
# https://github.com/scwang90/SmartRefreshLayout
smartRefreshLayout = "2.1.0"
# https://github.com/afollestad/material-dialogs
dialog = "3.3.0" # ä½œè€…å·²åœæ­¢ç»´æŠ¤
# https://github.com/AigeStudio/WheelPicker
# ä¸€ä¸ªæ»šè½®é€‰æ‹©å™¨
wheelPicker = "1.1.3"
# https://github.com/wangjiegulu/WheelView
# æœ‰æ˜¯ä¸€ä¸ªæ»šè½®é€‰æ‹©å™¨ï¼ˆä¸ºä»€ä¹ˆä¼šæœ‰å¤šä¸ªï¼Ÿæˆ‘ä¹Ÿä¸çŸ¥é“ï¼Œä½†è¿™ä¸ª 17 å¹´åå°±æ²¡ç»´æŠ¤äº†ï¼‰
wheelView = "4.1.9"

####################################################################################################
#                                              Kotlin
####################################################################################################
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.0.21"
# https://github.com/google/ksp/releases
ksp = "2.0.21-1.0.26" # ksp ç‰ˆæœ¬ä¸ kotlin ç‰ˆæœ¬å¼ºç»‘å®šï¼Œå‡çº§ kotlin è®°å¾—å»æ›´ ksp
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.9.0"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinx-collections = "0.3.8"
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = "1.7.3"

####################################################################################################
#                                               ä¸‰æ–¹åº“
####################################################################################################
# https://developer.umeng.com/docs/67966/detail/206987
umeng = "+"
# https://github.com/Tencent/VasDolly
vasdolly = "3.0.6"
# https://github.com/alibaba/ARouter
arouter = "1.5.2"
# https://github.com/JailedBird/ArouterKspCompiler
# ARouter çš„ç¬¬ä¸‰æ–¹ ksp å®ç°
arouter-ksp = "1.9.22-1.0.7"
# https://github.com/google/auto
autoService = "1.1.1"
# å…·ä½“å‚è€ƒè‡ªå®˜æ–¹æ–‡æ¡£ https://bugly.qq.com/v2/index
# å…¶ä¸­æŒé‚®æ¥å…¥äº† å¼‚å¸¸ä¸ŠæŠ¥ å’Œ åº”ç”¨å‡çº§ ä¸¤ä¸ªåŠŸèƒ½ï¼Œæ³¨æ„çœ‹å®Œå®˜ç½‘æ–‡æ¡£
bugly = "latest.release"
# https://github.com/greenrobot/EventBus
eventBus = "3.3.1"
# https://github.com/bumptech/glide/releases
glide = "4.16.0"
# https://github.com/limuyang2/LPhotoPicker
# ä¸€ä¸ªå›¾ç‰‡é€‰æ‹©æ¡†æ¶ï¼ˆä¸çŸ¥é“ä¸ºä»€ä¹ˆä»¥å‰å­¦é•¿ä¼šé€‰æ‹©è¿™ä¸ªï¼‰
lPhotoPicker = "2.7"
# https://github.com/Yalantis/uCrop
# ä¸€ä¸ªè£å‰ªå›¾ç‰‡çš„åº“
ucrop = "2.2.9-native"
# https://github.com/square/retrofit
retrofit = "2.11.0"
# https://github.com/square/okhttp
okhttp = "4.12.0"
# https://github.com/google/gson
gson = "2.11.0"
# https://github.com/ReactiveX/RxJava
rxjava = "3.1.9"
# https://github.com/ReactiveX/RxAndroid
rxjava-android = "3.0.2"
# https://github.com/ReactiveX/RxKotlin
rxjava-kotlin = "3.0.1"
# https://github.com/tbruyelle/RxPermissions
rxpermissions = "0.12" # ä½œè€… 20 å¹´å·²åœæ­¢ç»´æŠ¤
# https://github.com/square/leakcanary
leakcanary = "2.13"
# https://www.wanandroid.com/blog/show/2526
pandora = "androidx_v2.1.0"
# https://help.aliyun.com/document_detail/434554.html?spm=a2c4g.435252.0.0.1da95979yyEzm3
# é˜¿é‡Œäº‘httpdnsä¾èµ–
alicloud-httpdns = "2.3.2"
# https://github.com/mozilla/rhino
# js å¼•æ“ï¼Œæ”¯æŒä¸ java ç›´æ¥è¿›è¡Œäº¤äº’
rhino = "1.7.15"

[libraries]
####################################################################################################
#                                              Android
####################################################################################################
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycle-reactivestreams-ktx = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-animation = { module = "androidx.core:core-animation", version.ref = "androidx-core-animation" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-ktx" }

######################################## ç‰¹æ®Šä¾èµ–ï¼Œå°‘é‡æ¨¡å—å¼•å…¥ ########################################
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-databinding = { module = "androidx.databinding:databinding-runtime", version.ref = "androidx-databinding" }
androidx-databinding-ktx = { module = "androidx.databinding:databinding-ktx", version.ref = "androidx-databinding" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-rxjava = { module = "androidx.paging:paging-runtime-rxjava3", version.ref = "androidx-paging" }
androidx-room = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-room-rxjava = { module = "androidx.room:room-rxjava3", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }

####################################################################################################
#                                                æ§ä»¶
####################################################################################################
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
netLayout = { module = "io.github.985892345:NetLayout", version.ref = "netLayout" }
slideShow = { module = "io.github.985892345:SlideShow", version.ref = "slideShow" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
dialog = { module = "com.afollestad.material-dialogs:core", version.ref = "dialog" }
wheelPicker = { module = "cn.aigestudio.wheelpicker:WheelPicker", version.ref = "wheelPicker" }
wheelView = { module = "com.github.gzu-liyujiang.AndroidPicker:WheelView", version.ref = "wheelView" }
smartRefreshLayout = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "smartRefreshLayout" }
smartRefreshLayout-header-classics = { module = "io.github.scwang90:refresh-header-classics", version.ref = "smartRefreshLayout" }      # ç»å…¸åˆ·æ–°å¤´
smartRefreshLayout-header-radar = { module = "io.github.scwang90:refresh-header-radar", version.ref = "smartRefreshLayout" }            # é›·è¾¾åˆ·æ–°å¤´
smartRefreshLayout-header-falsify = { module = "io.github.scwang90:refresh-header-falsify", version.ref = "smartRefreshLayout" }        # è™šæ‹Ÿåˆ·æ–°å¤´
smartRefreshLayout-header-material = { module = "io.github.scwang90:refresh-header-material", version.ref = "smartRefreshLayout" }      # è°·æ­Œåˆ·æ–°å¤´
smartRefreshLayout-header-two-level = { module = "io.github.scwang90:refresh-header-two-level", version.ref = "smartRefreshLayout" }    # äºŒçº§åˆ·æ–°å¤´
smartRefreshLayout-footer-classics = { module = "io.github.scwang90:refresh-footer-classics", version.ref = "smartRefreshLayout" }      # ç»å…¸åŠ è½½
smartRefreshLayout-footer-ball = { module = "io.github.scwang90:refresh-footer-ball", version.ref = "smartRefreshLayout" }              # çƒè„‰å†²åŠ è½½

####################################################################################################
#                                               Kotlin
####################################################################################################
# gradlePlugin æ‰¾ä¸åˆ°çš„è¯å¯ä»¥è¿› pom æ–‡ä»¶è¿›è¡ŒæŸ¥çœ‹ï¼šhttps://repo1.maven.org/maven2/org/jetbrains/kotlin/plugin/
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines" }                # åŒ…å« Flow ä¸ Rxjava3 çš„äº’è½¬
kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

####################################################################################################
#                                               ä¸‰æ–¹åº“
####################################################################################################

######################################## ç‰¹æ®Šä¾èµ–ï¼Œå°‘é‡æ¨¡å—å¼•å…¥ ########################################
umeng = { module = "com.umeng.umsdk:common", version.ref = "umeng" }
umeng-asms = { module = "com.umeng.umsdk:asms", version.ref = "umeng" }
umeng-push = { module = "com.umeng.umsdk:push", version.ref = "umeng" } # å‹ç›Ÿçš„ push çœŸèƒ½ç”¨å—ï¼Ÿ
vasdolly = { module = "com.tencent.vasdolly:helper", version.ref = "vasdolly" }
vasdolly-gradlePlugin = { module = "com.tencent.vasdolly:plugin", version.ref = "vasdolly" }
bugly-crash = { module = "com.tencent.bugly:crashreport_upgrade", version.ref = "bugly" }
bugly-crash-native = { module = "com.tencent.bugly:nativecrashreport", version.ref = "bugly" }
lPhotoPicker = { module = "com.github.limuyang2:LPhotoPicker", version.ref = "lPhotoPicker" }           # æœ¬åœ°å›¾ç‰‡é€‰æ‹©
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }                                 # å›¾ç‰‡è£å‰ª
rxpermissions = { module = "com.github.tbruyelle:rxpermissions", version.ref = "rxpermissions" }        # æƒé™ç”³è¯·
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }      # å†…å­˜æ³„æ¼
pandora = { module = "com.github.whataa:pandora", version.ref = "pandora" }         # å¾ˆç‰›é€¼çš„ debug æ£€æµ‹å·¥å…·ï¼Œdebug æ¨¡å¼ä¸‹æ‘‡ä¸€æ‘‡æ‰‹æœºæˆ–è€…æŒ‰ä¸‰æ¬¡æ‰‹æœºä¸­é—´é¡¶éƒ¨åŒºåŸŸè§¦å‘
alicloud-httpdns = { module = "com.aliyun.ams:alicloud-android-httpdns", version.ref = "alicloud-httpdns" }     # é˜¿é‡Œäº‘httpdnsä¾èµ–
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }         # js å¼•æ“ï¼Œæ”¯æŒä¸ java ç›´æ¥è¿›è¡Œäº¤äº’

####################################### å…¬æœ‰ä¾èµ–ï¼Œå¤§éƒ¨åˆ†æ¨¡å—ä½¿ç”¨ #######################################
arouter = { module = "com.alibaba:arouter-api", version.ref = "arouter" }
arouter-compiler = { module = "com.github.JailedBird:ArouterKspCompiler", version.ref = "arouter-ksp" }
autoService = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
autoService-compiler = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
eventBus = { module = "org.greenrobot:eventbus", version.ref = "eventBus" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" } # todo å¾…ç§»é™¤
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinxSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxjava-android = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxjava-android" }
rxjava-kotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxjava-kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
vasdolly = { id = "com.tencent.vasdolly" }

[bundles]
projectBase = [
    # Android åŸºç¡€ä¾èµ–
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-process",
    "androidx-lifecycle-service",
    "androidx-lifecycle-reactivestreams-ktx",
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-viewmodel-savedstate",
    "androidx-lifecycle-livedata-ktx",
    "androidx-core-ktx",
    "androidx-core-animation",
    "androidx-collection-ktx",
    "androidx-fragment-ktx",
    "androidx-activity-ktx",
    # Kotlin åŸºç¡€ä¾èµ–
    "kotlinx-coroutines",
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-rx3",
    "kotlinx-collections",
    "kotlinx-serialization", # æƒ³è¦åºåˆ—åŒ–è¿˜éœ€è¦å¼•å…¥ kotlin-serialization æ’ä»¶
    # rxjava æ‰€æœ‰æ¨¡å—éƒ½éœ€è¦
    "rxjava",
    "rxjava-android",
    "rxjava-kotlin",
    # è·¯ç”±åŠæœåŠ¡æä¾›æ‰€æœ‰æ¨¡å—éƒ½éœ€è¦
    "arouter",
    "autoService"
]

views = [
    "androidx-constraintlayout",
    "androidx-recyclerview",
    "androidx-cardview",
    "androidx-viewpager2",
    "androidx-swiperefreshlayout",
    "material",
    "flexbox",
]

network = [
    "okhttp",
    "retrofit",
    "gson",
    "rxjava",
    "rxjava-android",
    "rxjava-kotlin",
]

# æ¯”è¾ƒå‡ºåçš„åˆ·æ–°æ§ä»¶ https://github.com/scwang90/SmartRefreshLayout
# ä½†å®‰å“è‡ªå¸¦çš„ Swiperefreshlayout ä¹Ÿèƒ½æ»¡è¶³å¤§éƒ¨åˆ†éœ€æ±‚
smartRefreshLayouts = [
    "smartRefreshLayout",
    "smartRefreshLayout-header-classics",
    "smartRefreshLayout-header-radar",
    "smartRefreshLayout-header-falsify",
    "smartRefreshLayout-header-material",
    "smartRefreshLayout-header-two-level",
    "smartRefreshLayout-footer-classics",
    "smartRefreshLayout-footer-ball",
]



